import type {
  MaterialProfile,
  PrinterProfile,
  PrintProfile,
} from '../../../types/slicer';
import type { StartupOptions } from '../../../types/slicer-gcode-startup.types';
import { resolveGCodeTemplate } from './runtime';
import {
  dedupeStartGCode,
  fanSpeedToCommandArg,
  restorePostStartModes,
  syncStateFromGCode,
} from './startEnd';

export function appendHeaderPlaceholders(
  gcode: string[],
  printer: PrinterProfile,
  material: MaterialProfile,
  print: PrintProfile,
): void {
  gcode.push('; Generated by Dzign3D Slicer');
  gcode.push('; PRINT_TIME_PLACEHOLDER');
  gcode.push('; FILAMENT_USED_PLACEHOLDER');
  gcode.push(`; Layer height: ${print.layerHeight}mm`);
  gcode.push(`; Nozzle: ${printer.nozzleDiameter}mm`);
  gcode.push(`; Infill: ${print.infillDensity}% ${print.infillPattern}`);
  gcode.push(`; Material: ${material.name}`);
  gcode.push(`; Printer: ${printer.name}`);
  gcode.push('');
}

export function appendStartGCode({
  gcode,
  printer,
  material: mat,
  print: pp,
  relativeExtrusion,
  flavor,
  startEndState,
}: StartupOptions): void {
  const isRRF = flavor === 'duet' || flavor === 'reprap';
  const isKlipper = flavor === 'klipper';
  const fanSArg = (pct: number): string => fanSpeedToCommandArg(printer.scaleFanSpeedTo01, pct);

  const startGCode = resolveGCodeTemplate(printer.startGCode, {
    nozzleTemp: mat.nozzleTempFirstLayer,
    nozzleTempFirstLayer: mat.nozzleTempFirstLayer,
    bedTemp: mat.bedTempFirstLayer,
    bedTempFirstLayer: mat.bedTempFirstLayer,
  });
  const startTemplateHasPrintMacro = /^\s*START_PRINT\b/m.test(startGCode);
  const startTemplateOwnsHeatup = printer.startGCodeMustBeFirst && startTemplateHasPrintMacro;

  gcode.push('; ----- Start G-code -----');
  if (printer.startGCodeMustBeFirst && startGCode.trim()) {
    gcode.push(startGCode.trim());
    syncStateFromGCode(startGCode, startEndState);
  }
  if (!startTemplateOwnsHeatup) {
    gcode.push('G90 ; Absolute positioning');
    gcode.push(relativeExtrusion ? 'M83 ; Relative extrusion' : 'M82 ; Absolute extrusion');
  }

  const hasInitTemp = mat.initialPrintingTemperature !== undefined
    && mat.initialPrintingTemperature !== mat.nozzleTempFirstLayer;
  const preheatTemp = hasInitTemp ? mat.initialPrintingTemperature! : mat.nozzleTempFirstLayer;
  const normalizedStartGCode = printer.startGCodeMustBeFirst
    ? startGCode.trim()
    : dedupeStartGCode(startGCode, {
      preheatTemp,
      nozzleFirstLayerTemp: mat.nozzleTempFirstLayer,
      bedFirstLayerTemp: mat.bedTempFirstLayer,
      relativeExtrusion,
      hasHeatedBed: printer.hasHeatedBed,
      waitForNozzle: printer.waitForNozzle ?? true,
      waitForBuildPlate: printer.waitForBuildPlate ?? true,
    });

  if (!startTemplateOwnsHeatup) {
    gcode.push(`M104 S${preheatTemp} ; Preheat nozzle`);
    if (printer.hasHeatedBed) {
      gcode.push(`M140 S${mat.bedTempFirstLayer} ; Set bed temp`);
    }
    if ((pp.buildVolumeFanSpeed ?? 0) > 0 || (pp.initialLayersBuildVolumeFanSpeed ?? 0) > 0) {
      const initBVF = pp.initialLayersBuildVolumeFanSpeed ?? pp.buildVolumeFanSpeed ?? 0;
      if (initBVF > 0) {
        gcode.push(`M106 P2 S${fanSArg(initBVF)} ; Build volume fan (initial layers)`);
      }
    }
    if (printer.hasHeatedBed) {
      const bedCmd = (printer.waitForBuildPlate ?? true) ? 'M190' : 'M140';
      gcode.push(`${bedCmd} S${mat.bedTempFirstLayer} ; ${(printer.waitForBuildPlate ?? true) ? 'Wait for' : 'Set'} bed temp`);
    }
    if (hasInitTemp) {
      gcode.push(`M104 S${mat.nozzleTempFirstLayer} ; Ramp to full nozzle temp`);
    }
    if (printer.hasHeatedChamber && mat.chamberTemp > 0) {
      gcode.push(`M141 S${mat.chamberTemp} ; Set chamber temp`);
    }
    const nozzleWaitCmd = (printer.waitForNozzle ?? true) ? 'M109' : 'M104';
    gcode.push(`${nozzleWaitCmd} S${mat.nozzleTempFirstLayer} ; ${(printer.waitForNozzle ?? true) ? 'Wait for' : 'Set'} nozzle temp`);
  }

  if (mat.linearAdvanceEnabled && (mat.linearAdvanceFactor ?? 0) >= 0) {
    const k = (mat.linearAdvanceFactor ?? 0).toFixed(3);
    if (isRRF) {
      gcode.push(`M572 D0 S${k} ; Pressure advance`);
    } else if (isKlipper) {
      gcode.push(`SET_PRESSURE_ADVANCE ADVANCE=${k} ; Pressure advance`);
    } else {
      gcode.push(`M900 K${k} ; Linear advance`);
    }
  }

  const hasM203 = [printer.maxSpeedX, printer.maxSpeedY, printer.maxSpeedZ, printer.maxSpeedE].some((v) => v !== undefined);
  if (hasM203) {
    const scale = isRRF ? 60 : 1;
    const fmt = (v: number) => (isRRF ? Math.round(v * scale).toString() : v.toString());
    const x = printer.maxSpeedX != null ? ` X${fmt(printer.maxSpeedX)}` : '';
    const y = printer.maxSpeedY != null ? ` Y${fmt(printer.maxSpeedY)}` : '';
    const z = printer.maxSpeedZ != null ? ` Z${fmt(printer.maxSpeedZ)}` : '';
    const e = printer.maxSpeedE != null ? ` E${fmt(printer.maxSpeedE)}` : '';
    gcode.push(`M203${x}${y}${z}${e} ; Max axis speeds${isRRF ? ' (mm/min)' : ' (mm/s)'}`);
  }

  const hasM201 = [printer.maxAccelX, printer.maxAccelY, printer.maxAccelZ, printer.maxAccelE].some((v) => v !== undefined);
  if (hasM201) {
    const x = printer.maxAccelX != null ? ` X${printer.maxAccelX}` : '';
    const y = printer.maxAccelY != null ? ` Y${printer.maxAccelY}` : '';
    const z = printer.maxAccelZ != null ? ` Z${printer.maxAccelZ}` : '';
    const e = printer.maxAccelE != null ? ` E${printer.maxAccelE}` : '';
    gcode.push(`M201${x}${y}${z}${e} ; Max axis accelerations`);
  }

  if (printer.defaultAcceleration != null) {
    gcode.push(`M204 S${printer.defaultAcceleration} ; Default acceleration`);
  }
  if (printer.defaultJerk != null) {
    if (isRRF) {
      const mmPerMin = Math.round(printer.defaultJerk * 60);
      gcode.push(`M566 X${mmPerMin} Y${mmPerMin} ; Default jerk (RRF instantaneous speed change)`);
    } else if (isKlipper) {
      gcode.push(`SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=${printer.defaultJerk} ; Default jerk (Klipper SCV)`);
    } else {
      gcode.push(`M205 X${printer.defaultJerk} Y${printer.defaultJerk} ; Default jerk`);
    }
  }

  if (!printer.startGCodeMustBeFirst && normalizedStartGCode) {
    gcode.push(normalizedStartGCode);
    syncStateFromGCode(normalizedStartGCode, startEndState);
  }
  restorePostStartModes(gcode, startEndState, relativeExtrusion);

  if (pp.primeBlobEnable) {
    const blobMm3 = pp.primeBlobSize ?? 0.5;
    const filArea = Math.PI * (printer.filamentDiameter / 2) ** 2;
    const blobE = (blobMm3 / filArea).toFixed(5);
    const blobF = (pp.firstLayerSpeed * 60).toFixed(0);
    gcode.push('; Prime blob');
    gcode.push(`G1 E${blobE} F${blobF} ; Prime blob extrusion`);
    gcode.push('G92 E0 ; Reset extruder after blob');
  }

  gcode.push('');
}
