import { useEffect, useState } from 'react';
import { Image, Loader2, X } from 'lucide-react';
import { usePrinterStore } from '../../../store/printerStore';
import type { DuetGCodeFileInfo } from '../../../types/duet';
import { formatFileSize } from '../../../utils/printerFormat';
import { formatDate, formatDuration, formatFilament } from './helpers';

export function FileInfoPanel({
  fileInfo,
  onClose,
}: {
  fileInfo: DuetGCodeFileInfo;
  onClose: () => void;
}) {
  const service = usePrinterStore((s) => s.service);
  const [thumbnailSrc, setThumbnailSrc] = useState<string | null>(null);
  const [thumbnailLoading, setThumbnailLoading] = useState(false);

  useEffect(() => {
    setThumbnailSrc(null);
    if (!service || !fileInfo.thumbnails || fileInfo.thumbnails.length === 0) return;

    const largest = [...fileInfo.thumbnails].sort(
      (a, b) => b.width * b.height - a.width * a.height,
    )[0];

    let cancelled = false;
    setThumbnailLoading(true);

    service
      .getThumbnail(fileInfo.fileName, largest.offset)
      .then((dataUrl) => {
        if (!cancelled && dataUrl) setThumbnailSrc(dataUrl);
      })
      .catch(() => {})
      .finally(() => {
        if (!cancelled) setThumbnailLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [service, fileInfo.fileName, fileInfo.thumbnails]);

  const rows: [string, string][] = [
    ['File', fileInfo.fileName.split('/').pop() || fileInfo.fileName],
    ['Size', formatFileSize(fileInfo.size)],
    ['Generated by', fileInfo.generatedBy || '--'],
    ['Object height', fileInfo.height > 0 ? `${fileInfo.height} mm` : '--'],
    ['Layer height', fileInfo.layerHeight > 0 ? `${fileInfo.layerHeight} mm` : '--'],
    ['First layer', fileInfo.firstLayerHeight > 0 ? `${fileInfo.firstLayerHeight} mm` : '--'],
    ['Layers', fileInfo.numLayers > 0 ? String(fileInfo.numLayers) : '--'],
    ['Print time (slicer)', formatDuration(fileInfo.printTime)],
    ['Simulated time', formatDuration(fileInfo.simulatedTime)],
    ['Last modified', formatDate(fileInfo.lastModified)],
  ];

  if (fileInfo.filament && fileInfo.filament.length > 0) {
    fileInfo.filament.forEach((mm, i) => {
      const label = fileInfo.filament.length === 1 ? 'Filament' : `Filament E${i}`;
      rows.push([label, formatFilament(mm)]);
    });
  }

  return (
    <div className="duet-file-mgr__info-panel">
      <button className="duet-file-mgr__close-info-btn" onClick={onClose} title="Close info panel">
        <X size={14} />
      </button>

      {fileInfo.thumbnails && fileInfo.thumbnails.length > 0 && (
        <div className="duet-file-mgr__thumbnail-center">
          {thumbnailLoading ? (
            <div className="duet-file-mgr__thumbnail-loading">
              <Loader2 size={16} className="spin" />
              Loading preview...
            </div>
          ) : thumbnailSrc ? (
            <img src={thumbnailSrc} alt="G-code thumbnail" className="duet-file-mgr__thumbnail" />
          ) : (
            <>
              <Image size={48} style={{ color: 'var(--border-strong)' }} />
              <div className="duet-file-mgr__thumbnail-caption">
                Thumbnail ({fileInfo.thumbnails[0].width}x{fileInfo.thumbnails[0].height})
              </div>
            </>
          )}
        </div>
      )}

      <div className="duet-file-mgr__info-panel-title">
        {fileInfo.fileName.split('/').pop() || fileInfo.fileName}
      </div>

      {rows.map(([label, value]) => (
        <div key={label} className="duet-file-mgr__info-row">
          <span className="duet-file-mgr__info-label">{label}</span>
          <span className="duet-file-mgr__info-value">{value}</span>
        </div>
      ))}
    </div>
  );
}
