import type { MaterialProfile, PrintProfile, PrinterProfile } from './profiles';

export const DEFAULT_PRINTER_PROFILES: PrinterProfile[] = [
  {
    id: 'custom-fff',
    name: 'Custom FFF Printer',
    buildVolume: { x: 100, y: 100, z: 100 },
    nozzleDiameter: 0.4,
    nozzleCount: 1,
    filamentDiameter: 2.85,
    hasHeatedBed: true,
    hasHeatedChamber: false,
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    maxSpeed: 200,
    maxAcceleration: 3000,
    originCenter: false,
    gcodeFlavorType: 'marlin',
    buildPlateShape: 'rectangular',
    printheadMinX: -20,
    printheadMinY: -10,
    printheadMaxX: 10,
    printheadMaxY: 10,
    gantryHeight: 100,
    applyExtruderOffsets: true,
    startGCodeMustBeFirst: false,
    extruderOffsetX: 0,
    extruderOffsetY: 0,
    coolingFanNumber: 0,
    printTimeEstimationFactor: 1.0,
    startGCode:
      'G28 ;Home\n' +
      'G1 Z15.0 F6000 ;Move the platform down 15mm\n' +
      ';Prime the extruder\n' +
      'G92 E0\n' +
      'G1 F200 E3\n' +
      'G92 E0\n',
    endGCode:
      'M104 S0\n' +
      'M140 S0\n' +
      ';Retract the filament\n' +
      'G92 E1\n' +
      'G1 E-1 F300\n' +
      'G28 X0 Y0\n' +
      'M84\n',
  },
  {
    id: 'duet3d-generic',
    name: 'Duet3D Generic',
    buildVolume: { x: 300, y: 300, z: 300 },
    nozzleDiameter: 0.4,
    nozzleCount: 1,
    filamentDiameter: 1.75,
    hasHeatedBed: true,
    hasHeatedChamber: false,
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    maxSpeed: 300,
    maxAcceleration: 3000,
    originCenter: false,
    gcodeFlavorType: 'duet',
    startGCode:
      '; Start G-code for Duet3D\n' +
      'G28 ; Home all axes\n' +
      'G29 S1 ; Load height map\n' +
      'M116 ; Wait for temperatures\n' +
      'G1 Z5 F3000 ; Lift nozzle\n' +
      'G1 X0 Y0 F3000 ; Move to start position\n' +
      'G92 E0 ; Reset extruder\n',
    endGCode:
      '; End G-code for Duet3D\n' +
      'G91 ; Relative positioning\n' +
      'G1 E-2 F2700 ; Retract\n' +
      'G1 Z10 F3000 ; Lift\n' +
      'G90 ; Absolute positioning\n' +
      'G1 X0 Y300 F3000 ; Present print\n' +
      'M104 S0 ; Heater off\n' +
      'M140 S0 ; Bed off\n' +
      'M106 S0 ; Fan off\n' +
      'M84 ; Motors off\n',
  },
  {
    id: 'marlin-generic',
    name: 'Marlin Generic',
    buildVolume: { x: 220, y: 220, z: 250 },
    nozzleDiameter: 0.4,
    nozzleCount: 1,
    filamentDiameter: 1.75,
    hasHeatedBed: true,
    hasHeatedChamber: false,
    maxNozzleTemp: 260,
    maxBedTemp: 110,
    maxSpeed: 200,
    maxAcceleration: 2000,
    originCenter: false,
    gcodeFlavorType: 'marlin',
    startGCode:
      '; Start G-code for Marlin\n' +
      'G90 ; Absolute positioning\n' +
      'M82 ; Absolute extrusion\n' +
      'M104 S{nozzleTemp} ; Set nozzle temp\n' +
      'M140 S{bedTemp} ; Set bed temp\n' +
      'M190 S{bedTemp} ; Wait for bed temp\n' +
      'M109 S{nozzleTemp} ; Wait for nozzle temp\n' +
      'G28 ; Home all axes\n' +
      'G29 ; Auto bed leveling\n' +
      'G92 E0 ; Reset extruder\n' +
      'G1 Z5 F3000 ; Lift nozzle\n' +
      'G1 X0.1 Y20 F5000 ; Move to prime position\n' +
      'G1 Z0.3 F3000 ; Lower nozzle\n' +
      'G1 X0.1 Y150 E15 F1500 ; Prime line\n' +
      'G1 X0.4 Y150 F5000 ; Move over\n' +
      'G1 X0.4 Y20 E30 F1500 ; Second prime line\n' +
      'G92 E0 ; Reset extruder\n' +
      'G1 Z2 F3000 ; Lift nozzle\n',
    endGCode:
      '; End G-code for Marlin\n' +
      'G91 ; Relative positioning\n' +
      'G1 E-2 F2700 ; Retract\n' +
      'G1 Z10 F3000 ; Lift nozzle\n' +
      'G90 ; Absolute positioning\n' +
      'G1 X0 Y200 F3000 ; Move bed forward\n' +
      'M104 S0 ; Turn off nozzle\n' +
      'M140 S0 ; Turn off bed\n' +
      'M107 ; Turn off fan\n' +
      'M84 ; Disable steppers\n',
  },
  {
    id: 'klipper-generic',
    name: 'Klipper Generic',
    buildVolume: { x: 250, y: 250, z: 300 },
    nozzleDiameter: 0.4,
    nozzleCount: 1,
    filamentDiameter: 1.75,
    hasHeatedBed: true,
    hasHeatedChamber: false,
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    maxSpeed: 500,
    maxAcceleration: 5000,
    originCenter: false,
    gcodeFlavorType: 'klipper',
    startGCodeMustBeFirst: true,
    startGCode:
      '; Start G-code for Klipper\n' +
      'START_PRINT BED_TEMP={bedTemp} EXTRUDER_TEMP={nozzleTemp}\n',
    endGCode:
      '; End G-code for Klipper\n' +
      'END_PRINT\n',
  },
];

export const DEFAULT_MATERIAL_PROFILES: MaterialProfile[] = [
  {
    id: 'pla-generic',
    name: 'PLA Generic',
    type: 'PLA',
    color: '#4fc3f7',
    nozzleTemp: 210,
    nozzleTempFirstLayer: 215,
    bedTemp: 60,
    bedTempFirstLayer: 65,
    chamberTemp: 0,
    fanSpeedMin: 100,
    fanSpeedMax: 100,
    fanDisableFirstLayers: 1,
    retractionDistance: 0.8,
    retractionSpeed: 45,
    retractionZHop: 0.2,
    flowRate: 1.0,
    density: 1.24,
    costPerKg: 20,
  },
  {
    id: 'abs-generic',
    name: 'ABS Generic',
    type: 'ABS',
    color: '#e0e0e0',
    nozzleTemp: 240,
    nozzleTempFirstLayer: 245,
    bedTemp: 100,
    bedTempFirstLayer: 105,
    chamberTemp: 50,
    fanSpeedMin: 0,
    fanSpeedMax: 30,
    fanDisableFirstLayers: 3,
    retractionDistance: 0.8,
    retractionSpeed: 40,
    retractionZHop: 0.2,
    flowRate: 1.0,
    density: 1.04,
    costPerKg: 22,
  },
  {
    id: 'petg-generic',
    name: 'PETG Generic',
    type: 'PETG',
    color: '#81c784',
    nozzleTemp: 230,
    nozzleTempFirstLayer: 235,
    bedTemp: 80,
    bedTempFirstLayer: 85,
    chamberTemp: 0,
    fanSpeedMin: 50,
    fanSpeedMax: 70,
    fanDisableFirstLayers: 2,
    retractionDistance: 1.0,
    retractionSpeed: 40,
    retractionZHop: 0.2,
    flowRate: 1.0,
    density: 1.27,
    costPerKg: 25,
  },
  {
    id: 'tpu-generic',
    name: 'TPU Generic',
    type: 'TPU',
    color: '#ff8a65',
    nozzleTemp: 225,
    nozzleTempFirstLayer: 230,
    bedTemp: 50,
    bedTempFirstLayer: 55,
    chamberTemp: 0,
    fanSpeedMin: 50,
    fanSpeedMax: 70,
    fanDisableFirstLayers: 2,
    retractionDistance: 0.5,
    retractionSpeed: 25,
    retractionZHop: 0.1,
    flowRate: 1.05,
    density: 1.21,
    costPerKg: 35,
  },
  {
    id: 'asa-generic',
    name: 'ASA Generic',
    type: 'ASA',
    color: '#b0bec5',
    nozzleTemp: 250,
    nozzleTempFirstLayer: 255,
    bedTemp: 100,
    bedTempFirstLayer: 105,
    chamberTemp: 40,
    fanSpeedMin: 0,
    fanSpeedMax: 40,
    fanDisableFirstLayers: 3,
    retractionDistance: 0.8,
    retractionSpeed: 40,
    retractionZHop: 0.2,
    flowRate: 1.0,
    density: 1.07,
    costPerKg: 30,
  },
  {
    id: 'nylon-generic',
    name: 'Nylon Generic',
    type: 'Nylon',
    color: '#ffe082',
    nozzleTemp: 260,
    nozzleTempFirstLayer: 265,
    bedTemp: 80,
    bedTempFirstLayer: 85,
    chamberTemp: 40,
    fanSpeedMin: 0,
    fanSpeedMax: 30,
    fanDisableFirstLayers: 3,
    retractionDistance: 1.2,
    retractionSpeed: 40,
    retractionZHop: 0.2,
    flowRate: 1.0,
    density: 1.14,
    costPerKg: 40,
  },
];

export const DEFAULT_PRINT_PROFILES: PrintProfile[] = [
  {
    id: 'standard-quality',
    name: 'Standard Quality (0.2mm)',
    layerHeight: 0.2,
    firstLayerHeight: 0.3,
    wallCount: 3,
    wallSpeed: 45,
    outerWallSpeed: 30,
    wallLineWidth: 0.45,
    topLayers: 4,
    bottomLayers: 4,
    topBottomPattern: 'lines',
    topSpeed: 40,
    infillDensity: 20,
    infillPattern: 'grid',
    infillSpeed: 60,
    infillLineWidth: 0.45,
    infillOverlap: 10,
    printSpeed: 50,
    travelSpeed: 150,
    firstLayerSpeed: 25,
    supportEnabled: false,
    supportType: 'normal',
    supportAngle: 50,
    supportDensity: 15,
    supportPattern: 'zigzag',
    supportZDistance: 0.2,
    supportXYDistance: 0.7,
    supportInterface: true,
    supportInterfaceLayers: 2,
    adhesionType: 'skirt',
    skirtLines: 3,
    skirtDistance: 5,
    brimWidth: 8,
    raftLayers: 3,
    enableBridgeFan: true,
    bridgeFanSpeed: 100,
    minLayerTime: 10,
    lineWidth: 0.4,
    outerWallLineWidth: 0.4,
    topBottomLineWidth: 0.4,
    initialLayerLineWidthFactor: 120,
    outerWallFirst: false,
    alternateExtraWall: false,
    infillWallCount: 0,
    gradualInfillSteps: 0,
    supportSpeed: 40,
    smallAreaSpeed: 20,
    retractionMinTravel: 1.5,
    minPrintSpeed: 10,
    fanFullLayer: 4,
    liftHeadEnabled: false,
    supportTreeAngle: 60,
    supportTreeBranchDiameter: 5,
    brimGap: 0,
    brimLocation: 'outside',
    raftMargin: 5,
    zSeamAlignment: 'sharpest_corner',
    combingMode: 'noskin',
    avoidCrossingPerimeters: false,
    thinWallDetection: true,
    ironingEnabled: false,
    ironingSpeed: 15,
    ironingFlow: 10,
    ironingSpacing: 0.1,
    spiralizeContour: false,
    printSequence: 'all_at_once',
    draftShieldEnabled: false,
    draftShieldDistance: 10,
    coastingEnabled: false,
    coastingVolume: 0.064,
    adaptiveLayersEnabled: false,
    adaptiveLayersMaxVariation: 0.1,
    adaptiveLayersVariationStep: 0.05,
    wallTransitionLength: 1.0,
    wallTransitionAngle: 10,
    minWallLineWidth: 0.2,
    outerWallWipeDistance: 0.0,
    zSeamX: null,
    zSeamY: null,
    roofingLayers: 0,
    roofingPattern: 'lines',
    monotonicTopBottomOrder: false,
    bridgeSkinSpeed: 25,
    bridgeSkinFlow: 60,
    bridgeAngle: 0,
    bridgeWallSpeed: 25,
    skinEdgeSupportLayers: 0,
    infillBeforeWalls: false,
    multiplyInfill: 1,
    randomInfillStart: false,
    lightningInfillSupportAngle: 40,
    accelerationEnabled: false,
    jerkEnabled: false,
    accelerationPrint: 3000,
    accelerationTravel: 3000,
    accelerationWall: 1000,
    accelerationInfill: 3000,
    accelerationTopBottom: 1000,
    accelerationSupport: 2000,
    jerkPrint: 10,
    jerkTravel: 10,
    jerkWall: 8,
    jerkInfill: 10,
    jerkTopBottom: 8,
    skirtBrimSpeed: 30,
    retractAtLayerChange: true,
    maxRetractionCount: 90,
    retractionExtraPrimeAmount: 0,
    combingAvoidsSupports: false,
    travelRetractBeforeOuterWall: false,
    coolingFanEnabled: true,
    regularFanSpeedLayer: 1,
    fanKickstartTime: 100,
    supportBuildplateOnly: false,
    supportRoofEnable: false,
    supportFloorEnable: false,
    supportBottomDistance: 0.2,
    supportWallCount: 0,
    supportInterfacePattern: 'lines',
    supportInterfaceDensity: 100,
    skirtHeight: 1,
    brimReplacesSupportEnabled: false,
    raftBaseThickness: 0.3,
    raftBaseLineWidth: 0.8,
    raftBaseSpeed: 20,
    raftInterfaceThickness: 0.27,
    raftInterfaceLineWidth: 0.4,
    raftInterfaceSpeed: 40,
    raftSurfaceThickness: 0.27,
    raftSurfaceLineWidth: 0.4,
    raftSurfaceSpeed: 40,
    raftAirGap: 0.3,
    unionOverlappingVolumes: true,
    removeAllHoles: false,
    extensiveStitching: false,
    keepDisconnectedFaces: false,
    maxResolution: 0.5,
    maxDeviation: 0.025,
    maxTravelResolution: 0.8,
    surfaceMode: 'normal',
    moldEnabled: false,
    moldAngle: 40,
    moldRoofHeight: 0.5,
    fuzzySkinsEnabled: false,
    fuzzySkinThickness: 0.3,
    fuzzySkinPointDist: 0.8,
    makeOverhangPrintable: false,
    makeOverhangPrintableMaxAngle: 50,
    slicingTolerance: 'middle',
    flowRateCompensationMaxExtrusion: 0.0,
    smallHoleMaxSize: 0.0,
    minimumPolygonCircumference: 1.0,
    slicingClosingRadius: 0.049,
  },
];
