import type { MaterialProfile, PrintProfile, PrinterProfile } from '../../types/slicer';

export interface CalibrationTowerContext {
  printer: PrinterProfile;
  material: MaterialProfile;
  print: PrintProfile;
}

export interface CalibrationBand<T> {
  startLayer: number;
  value: T;
}

export function formatNumber(value: number, digits = 3): string {
  return Number(value.toFixed(digits)).toString();
}

export function substituteTokens(template: string | undefined, ctx: CalibrationTowerContext): string {
  if (!template) return '';
  const tokens: Record<string, string> = {
    nozzleTemp: formatNumber(ctx.material.nozzleTemp),
    firstLayerNozzleTemp: formatNumber(ctx.material.nozzleTempFirstLayer ?? ctx.material.nozzleTemp),
    bedTemp: formatNumber(ctx.material.bedTemp),
    firstLayerBedTemp: formatNumber(ctx.material.bedTempFirstLayer ?? ctx.material.bedTemp),
    chamberTemp: formatNumber(ctx.material.chamberTemp ?? 0),
    layerHeight: formatNumber(ctx.print.layerHeight),
    firstLayerHeight: formatNumber(ctx.print.firstLayerHeight),
    printSpeed: formatNumber(ctx.print.printSpeed),
    travelSpeed: formatNumber(ctx.print.travelSpeed),
  };
  return template.replace(/\{([A-Za-z0-9_]+)\}/g, (_, key: string) => tokens[key] ?? '');
}

export function buildCalibrationHeader(
  title: string,
  ctx: CalibrationTowerContext,
  notes: string[],
): string[] {
  const start = substituteTokens(ctx.printer.startGCode, ctx);
  return [
    `; ${title}`,
    '; Generated by DesignCAD calibration tools',
    ...notes.map((note) => `; ${note}`),
    start.trim(),
    'G90',
    'M83',
  ].filter((line) => line.trim().length > 0);
}

export function buildCalibrationFooter(ctx: CalibrationTowerContext): string[] {
  const end = substituteTokens(ctx.printer.endGCode, ctx);
  return [
    'M82',
    end.trim(),
  ].filter((line) => line.trim().length > 0);
}

export function pressureAdvanceCommand(printer: PrinterProfile, value: number): string {
  const k = formatNumber(value, 4);
  if (printer.gcodeFlavorType === 'duet' || printer.gcodeFlavorType === 'reprap') {
    return `M572 D0 S${k}`;
  }
  if (printer.gcodeFlavorType === 'klipper') {
    return `SET_PRESSURE_ADVANCE ADVANCE=${k}`;
  }
  return `M900 K${k}`;
}

export function makeBands<T>(values: readonly T[], layersPerBand: number): CalibrationBand<T>[] {
  return values.map((value, index) => ({
    startLayer: index * layersPerBand,
    value,
  }));
}

export function bandValueAtLayer<T>(bands: CalibrationBand<T>[], layerIndex: number): T {
  let active = bands[0].value;
  for (const band of bands) {
    if (layerIndex >= band.startLayer) active = band.value;
    else break;
  }
  return active;
}

function filamentArea(printer: PrinterProfile): number {
  return Math.PI * Math.pow((printer.filamentDiameter ?? 1.75) / 2, 2);
}

export class RelativeExtrusionWriter {
  private readonly lines: string[];
  private readonly extrusionArea: number;
  private readonly flowMultiplier: number;

  constructor(lines: string[], ctx: CalibrationTowerContext, flowMultiplier = 1) {
    this.lines = lines;
    this.extrusionArea = filamentArea(ctx.printer);
    this.flowMultiplier = flowMultiplier * (ctx.material.flowRate ?? 1);
  }

  travel(x: number, y: number, feedrateMmPerMin: number): void {
    this.lines.push(`G0 X${formatNumber(x)} Y${formatNumber(y)} F${formatNumber(feedrateMmPerMin, 0)}`);
  }

  moveZ(z: number, feedrateMmPerMin: number): void {
    this.lines.push(`G0 Z${formatNumber(z)} F${formatNumber(feedrateMmPerMin, 0)}`);
  }

  extrudeTo(from: { x: number; y: number }, to: { x: number; y: number }, width: number, height: number, feedrateMmPerMin: number): void {
    const distance = Math.hypot(to.x - from.x, to.y - from.y);
    const volume = distance * width * height * this.flowMultiplier;
    const filament = volume / this.extrusionArea;
    this.lines.push(
      `G1 X${formatNumber(to.x)} Y${formatNumber(to.y)} E${formatNumber(filament, 5)} F${formatNumber(feedrateMmPerMin, 0)}`,
    );
  }

  extrudeAmount(amount: number, feedrateMmPerMin: number): void {
    this.lines.push(`G1 E${formatNumber(amount, 5)} F${formatNumber(feedrateMmPerMin, 0)}`);
  }
}
